# Application name
spring.application.name=backend

# Datasource config - use env vars if set, fallback to localhost defaults
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coffee_shop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Logging level for Spring Web
logging.level.org.springframework.web=DEBUG


server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/server-cert.pfx
server.ssl.key-store-password=development321
server.ssl.key-store-type=PKCS12

#vault
logging.level.com.example.backend.SpringSecurity.security=DEBUG
spring.cloud.vault.uri=http://vault:8200
spring.cloud.vault.authentication=token
spring.cloud.vault.token=myroot
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=backend
spring.cloud.vault.kv.default-context=jwt
spring.cloud.vault.kv.profile-separator=/
spring.config.import=vault://